version: "3.8"

services:
  client:
    build: ./apps/client
    ports:
      - 5173:5173
    volumes:
      - ./apps/client:/apps/client
      # https://stackoverflow.com/a/37898591
      # exclude node_modules due to Vite error
      - /app/client/node_modules/
    environment:
      - API_URL=http://localhost:3000/

  server:
    build: ./apps/server-raw
    ports:
      - 3000:3000
    volumes:
      - ./apps/server-raw:/apps/server-raw
      - /apps/server-raw/node_modules/
    environment:
      - PORT=3000
