// register or login

POST http://localhost:5000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email" : "boedhi@boedhi.com",
  "password" : "boedhi"
}

// get

GET http://localhost:5000/api/user/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSJ9.4NKyEEEmlGH3vu_LkZ0hvQBQr2lccBDQETfrOS-Pu5Q



// user

PATCH http://localhost:5000/api/user/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSJ9.4NKyEEEmlGH3vu_LkZ0hvQBQr2lccBDQETfrOS-Pu5Q

{
  "email" : "boedhi@boedhi.com",
  "username" : "boedhi",
  "password": "boedhi",
  "bio": "bio"
}
