// register or login

POST http://localhost:5000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email" : "boedhi@boedhi.com",
  "password" : "boedhi"
}

// get
GET http://localhost:4000/api/user/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSIsImlhdCI6MTY5ODk5NTA2NCwiZXhwIjoxNjk5NTk5ODY0fQ.jQ6KhWK2cCkdTmIqJOsH3iJwuvIy1PJQLAYUTG6kQ84


// user
PATCH http://localhost:4000/api/user/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSIsImlhdCI6MTY5ODk5NTA2NCwiZXhwIjoxNjk5NTk5ODY0fQ.jQ6KhWK2cCkdTmIqJOsH3iJwuvIy1PJQLAYUTG6kQ84

{
  "email" : "boedhi@boedhi.com",
  "username" : "wew",
  "bio": "moengngn"
}


// profile yourself
GET http://localhost:5000/api/user/boedhi
Content-Type: application/json
Accept: application/json

// profile other
GET http://localhost:5000/api/user/wew
Content-Type: application/json
Accept: application/json


// profile other with login
GET http://localhost:5000/api/user/wew
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSIsImlhdCI6MTY5OTA3NDA4MSwiZXhwIjoxNjk5Njc4ODgxfQ.2zaeN-HGe79rs8Cpv9GNx4uYkhT1AUhEaWwmjSLeKxI



// follow
POST http://localhost:5000/api/user/wew/follow
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSIsImlhdCI6MTY5OTA3NDA4MSwiZXhwIjoxNjk5Njc4ODgxfQ.2zaeN-HGe79rs8Cpv9GNx4uYkhT1AUhEaWwmjSLeKxI

// unfollow
POST http://localhost:5000/api/user/wew/unfollow
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYm9lZGhpIiwiZW1haWwiOiJib2VkaGlAYm9lZGhpLmNvbSIsImlhdCI6MTY5OTA3NDA4MSwiZXhwIjoxNjk5Njc4ODgxfQ.2zaeN-HGe79rs8Cpv9GNx4uYkhT1AUhEaWwmjSLeKxI

